[project]
name = "ai-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "luisotee", email = "luisotaviomgr1@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "docling>=2.64.0",
    "docling-core[chunking-openai]>=2.54.1",
    "fastapi>=0.122.0",
    "google-genai>=1.52.0",
    "litellm>=1.80.7",
    "numpy>=2.3.5",
    "pgvector>=0.3.6",
    "psycopg2-binary>=2.9.11",
    "pydantic-ai>=1.25.1",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.44",
    "tiktoken>=0.8.0",
    "uvicorn>=0.38.0",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
